/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/URI', 'model/UriBuilder'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./URI'), require('./UriBuilder'));
  } else {
    // Browser globals (root is window)
    if (!root.RecomaxRestApi) {
      root.RecomaxRestApi = {};
    }
    root.RecomaxRestApi.Link = factory(root.RecomaxRestApi.ApiClient, root.RecomaxRestApi.URI, root.RecomaxRestApi.UriBuilder);
  }
}(this, function(ApiClient, URI, UriBuilder) {
  'use strict';

  /**
   * The Link model module.
   * @module model/Link
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Link</code>.
   * @alias module:model/Link
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Link</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Link} obj Optional instance to populate.
   * @return {module:model/Link} The populated <code>Link</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('params'))
        obj.params = ApiClient.convertToType(data['params'], {'String': 'String'});
      if (data.hasOwnProperty('rel'))
        obj.rel = ApiClient.convertToType(data['rel'], 'String');
      if (data.hasOwnProperty('rels'))
        obj.rels = ApiClient.convertToType(data['rels'], ['String']);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('uri'))
        obj.uri = URI.constructFromObject(data['uri']);
      if (data.hasOwnProperty('uriBuilder'))
        obj.uriBuilder = UriBuilder.constructFromObject(data['uriBuilder']);
    }
    return obj;
  }

  /**
   * @member {Object.<String, String>} params
   */
  exports.prototype.params = undefined;

  /**
   * @member {String} rel
   */
  exports.prototype.rel = undefined;

  /**
   * @member {Array.<String>} rels
   */
  exports.prototype.rels = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {module:model/URI} uri
   */
  exports.prototype.uri = undefined;

  /**
   * @member {module:model/UriBuilder} uriBuilder
   */
  exports.prototype.uriBuilder = undefined;


  return exports;

}));
