/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Character'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Character'));
  } else {
    // Browser globals (root is window)
    if (!root.RecomaxRestApi) {
      root.RecomaxRestApi = {};
    }
    root.RecomaxRestApi.Locale = factory(root.RecomaxRestApi.ApiClient, root.RecomaxRestApi.Character);
  }
}(this, function(ApiClient, Character) {
  'use strict';

  /**
   * The Locale model module.
   * @module model/Locale
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Locale</code>.
   * @alias module:model/Locale
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Locale</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Locale} obj Optional instance to populate.
   * @return {module:model/Locale} The populated <code>Locale</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('displayCountry'))
        obj.displayCountry = ApiClient.convertToType(data['displayCountry'], 'String');
      if (data.hasOwnProperty('displayLanguage'))
        obj.displayLanguage = ApiClient.convertToType(data['displayLanguage'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('displayScript'))
        obj.displayScript = ApiClient.convertToType(data['displayScript'], 'String');
      if (data.hasOwnProperty('displayVariant'))
        obj.displayVariant = ApiClient.convertToType(data['displayVariant'], 'String');
      if (data.hasOwnProperty('extensionKeys'))
        obj.extensionKeys = ApiClient.convertToType(data['extensionKeys'], [Character]);
      if (data.hasOwnProperty('iso3Country'))
        obj.iso3Country = ApiClient.convertToType(data['iso3Country'], 'String');
      if (data.hasOwnProperty('iso3Language'))
        obj.iso3Language = ApiClient.convertToType(data['iso3Language'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('script'))
        obj.script = ApiClient.convertToType(data['script'], 'String');
      if (data.hasOwnProperty('unicodeLocaleAttributes'))
        obj.unicodeLocaleAttributes = ApiClient.convertToType(data['unicodeLocaleAttributes'], ['String']);
      if (data.hasOwnProperty('unicodeLocaleKeys'))
        obj.unicodeLocaleKeys = ApiClient.convertToType(data['unicodeLocaleKeys'], ['String']);
      if (data.hasOwnProperty('variant'))
        obj.variant = ApiClient.convertToType(data['variant'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} country
   */
  exports.prototype.country = undefined;

  /**
   * @member {String} displayCountry
   */
  exports.prototype.displayCountry = undefined;

  /**
   * @member {String} displayLanguage
   */
  exports.prototype.displayLanguage = undefined;

  /**
   * @member {String} displayName
   */
  exports.prototype.displayName = undefined;

  /**
   * @member {String} displayScript
   */
  exports.prototype.displayScript = undefined;

  /**
   * @member {String} displayVariant
   */
  exports.prototype.displayVariant = undefined;

  /**
   * @member {Array.<module:model/Character>} extensionKeys
   */
  exports.prototype.extensionKeys = undefined;

  /**
   * @member {String} iso3Country
   */
  exports.prototype.iso3Country = undefined;

  /**
   * @member {String} iso3Language
   */
  exports.prototype.iso3Language = undefined;

  /**
   * @member {String} language
   */
  exports.prototype.language = undefined;

  /**
   * @member {String} script
   */
  exports.prototype.script = undefined;

  /**
   * @member {Array.<String>} unicodeLocaleAttributes
   */
  exports.prototype.unicodeLocaleAttributes = undefined;

  /**
   * @member {Array.<String>} unicodeLocaleKeys
   */
  exports.prototype.unicodeLocaleKeys = undefined;

  /**
   * @member {String} variant
   */
  exports.prototype.variant = undefined;


  return exports;

}));
