/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RecomaxRestApi) {
      root.RecomaxRestApi = {};
    }
    root.RecomaxRestApi.MediaType = factory(root.RecomaxRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The MediaType model module.
   * @module model/MediaType
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MediaType</code>.
   * @alias module:model/MediaType
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>MediaType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaType} obj Optional instance to populate.
   * @return {module:model/MediaType} The populated <code>MediaType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], {'String': 'String'});
      if (data.hasOwnProperty('subtype'))
        obj.subtype = ApiClient.convertToType(data['subtype'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('wildcardSubtype'))
        obj.wildcardSubtype = ApiClient.convertToType(data['wildcardSubtype'], 'Boolean');
      if (data.hasOwnProperty('wildcardType'))
        obj.wildcardType = ApiClient.convertToType(data['wildcardType'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {Object.<String, String>} parameters
   */
  exports.prototype.parameters = undefined;

  /**
   * @member {String} subtype
   */
  exports.prototype.subtype = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {Boolean} wildcardSubtype
   */
  exports.prototype.wildcardSubtype = undefined;

  /**
   * @member {Boolean} wildcardType
   */
  exports.prototype.wildcardType = undefined;


  return exports;

}));
