/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RecomaxRestApi) {
      root.RecomaxRestApi = {};
    }
    root.RecomaxRestApi.NewCookie = factory(root.RecomaxRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NewCookie model module.
   * @module model/NewCookie
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>NewCookie</code>.
   * @alias module:model/NewCookie
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>NewCookie</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewCookie} obj Optional instance to populate.
   * @return {module:model/NewCookie} The populated <code>NewCookie</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
      if (data.hasOwnProperty('domain'))
        obj.domain = ApiClient.convertToType(data['domain'], 'String');
      if (data.hasOwnProperty('expiry'))
        obj.expiry = ApiClient.convertToType(data['expiry'], 'Date');
      if (data.hasOwnProperty('httpOnly'))
        obj.httpOnly = ApiClient.convertToType(data['httpOnly'], 'Boolean');
      if (data.hasOwnProperty('maxAge'))
        obj.maxAge = ApiClient.convertToType(data['maxAge'], 'Integer');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('secure'))
        obj.secure = ApiClient.convertToType(data['secure'], 'Boolean');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Integer');
    }
    return obj;
  }

  /**
   * @member {String} comment
   */
  exports.prototype.comment = undefined;

  /**
   * @member {String} domain
   */
  exports.prototype.domain = undefined;

  /**
   * @member {Date} expiry
   */
  exports.prototype.expiry = undefined;

  /**
   * @member {Boolean} httpOnly
   */
  exports.prototype.httpOnly = undefined;

  /**
   * @member {Integer} maxAge
   */
  exports.prototype.maxAge = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} path
   */
  exports.prototype.path = undefined;

  /**
   * @member {Boolean} secure
   */
  exports.prototype.secure = undefined;

  /**
   * @member {String} value
   */
  exports.prototype.value = undefined;

  /**
   * @member {Integer} version
   */
  exports.prototype.version = undefined;


  return exports;

}));
