/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Item'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Item'));
  } else {
    // Browser globals (root is window)
    if (!root.RecomaxRestApi) {
      root.RecomaxRestApi = {};
    }
    root.RecomaxRestApi.RecomResultItem = factory(root.RecomaxRestApi.ApiClient, root.RecomaxRestApi.Item);
  }
}(this, function(ApiClient, Item) {
  'use strict';

  /**
   * The RecomResultItem model module.
   * @module model/RecomResultItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RecomResultItem</code>.
   * @alias module:model/RecomResultItem
   * @class
   * @param item {module:model/Item} item
   * @param rank {Number} rank
   * @param recommendationId {String} recommendationId
   */
  var exports = function(item, rank, recommendationId) {
    this.item = item;
    this.rank = rank;
    this.recommendationId = recommendationId;
  };

  /**
   * Constructs a <code>RecomResultItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecomResultItem} obj Optional instance to populate.
   * @return {module:model/RecomResultItem} The populated <code>RecomResultItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('item'))
        obj.item = Item.constructFromObject(data['item']);
      if (data.hasOwnProperty('rank'))
        obj.rank = ApiClient.convertToType(data['rank'], 'Number');
      if (data.hasOwnProperty('recommendationId'))
        obj.recommendationId = ApiClient.convertToType(data['recommendationId'], 'String');
    }
    return obj;
  }

  /**
   * item
   * @member {module:model/Item} item
   */
  exports.prototype.item = undefined;

  /**
   * rank
   * @member {Number} rank
   */
  exports.prototype.rank = undefined;

  /**
   * recommendationId
   * @member {String} recommendationId
   */
  exports.prototype.recommendationId = undefined;


  return exports;

}));
