/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RecomResultItem', 'model/RecomVirtualCategory'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RecomResultItem'), require('./RecomVirtualCategory'));
  } else {
    // Browser globals (root is window)
    if (!root.RecomaxRestApi) {
      root.RecomaxRestApi = {};
    }
    root.RecomaxRestApi.RecomResult = factory(root.RecomaxRestApi.ApiClient, root.RecomaxRestApi.RecomResultItem, root.RecomaxRestApi.RecomVirtualCategory);
  }
}(this, function(ApiClient, RecomResultItem, RecomVirtualCategory) {
  'use strict';

  /**
   * The RecomResult model module.
   * @module model/RecomResult
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RecomResult</code>.
   * @alias module:model/RecomResult
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RecomResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecomResult} obj Optional instance to populate.
   * @return {module:model/RecomResult} The populated <code>RecomResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Integer');
      if (data.hasOwnProperty('recomVirtualCategoryList'))
        obj.recomVirtualCategoryList = ApiClient.convertToType(data['recomVirtualCategoryList'], [RecomVirtualCategory]);
      if (data.hasOwnProperty('searchResultItemList'))
        obj.searchResultItemList = ApiClient.convertToType(data['searchResultItemList'], [RecomResultItem]);
    }
    return obj;
  }

  /**
   * @member {Integer} count
   */
  exports.prototype.count = undefined;

  /**
   * @member {Array.<module:model/RecomVirtualCategory>} recomVirtualCategoryList
   */
  exports.prototype.recomVirtualCategoryList = undefined;

  /**
   * @member {Array.<module:model/RecomResultItem>} searchResultItemList
   */
  exports.prototype.searchResultItemList = undefined;


  return exports;

}));
