/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecomaxRestApi);
  }
}(this, function(expect, RecomaxRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MediaType', function() {
      beforeEach(function() {
        instance = new RecomaxRestApi.MediaType();
      });

      it('should create an instance of MediaType', function() {
        // TODO: update the code to test MediaType
        expect(instance).to.be.a(RecomaxRestApi.MediaType);
      });

      it('should have the property parameters (base name: "parameters")', function() {
        // TODO: update the code to test the property parameters
        expect(instance).to.have.property('parameters');
        // expect(instance.parameters).to.be(expectedValueLiteral);
      });

      it('should have the property subtype (base name: "subtype")', function() {
        // TODO: update the code to test the property subtype
        expect(instance).to.have.property('subtype');
        // expect(instance.subtype).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property wildcardSubtype (base name: "wildcardSubtype")', function() {
        // TODO: update the code to test the property wildcardSubtype
        expect(instance).to.have.property('wildcardSubtype');
        // expect(instance.wildcardSubtype).to.be(expectedValueLiteral);
      });

      it('should have the property wildcardType (base name: "wildcardType")', function() {
        // TODO: update the code to test the property wildcardType
        expect(instance).to.have.property('wildcardType');
        // expect(instance.wildcardType).to.be(expectedValueLiteral);
      });

    });
  });

}));
