/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecomaxRestApi);
  }
}(this, function(expect, RecomaxRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RecomResult', function() {
      beforeEach(function() {
        instance = new RecomaxRestApi.RecomResult();
      });

      it('should create an instance of RecomResult', function() {
        // TODO: update the code to test RecomResult
        expect(instance).to.be.a(RecomaxRestApi.RecomResult);
      });

      it('should have the property count (base name: "count")', function() {
        // TODO: update the code to test the property count
        expect(instance).to.have.property('count');
        // expect(instance.count).to.be(expectedValueLiteral);
      });

      it('should have the property recomVirtualCategoryList (base name: "recomVirtualCategoryList")', function() {
        // TODO: update the code to test the property recomVirtualCategoryList
        expect(instance).to.have.property('recomVirtualCategoryList');
        // expect(instance.recomVirtualCategoryList).to.be(expectedValueLiteral);
      });

      it('should have the property searchResultItemList (base name: "searchResultItemList")', function() {
        // TODO: update the code to test the property searchResultItemList
        expect(instance).to.have.property('searchResultItemList');
        // expect(instance.searchResultItemList).to.be(expectedValueLiteral);
      });

    });
  });

}));
