/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecomaxRestApi);
  }
}(this, function(expect, RecomaxRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RecomVirtualCategory', function() {
      beforeEach(function() {
        instance = new RecomaxRestApi.RecomVirtualCategory();
      });

      it('should create an instance of RecomVirtualCategory', function() {
        // TODO: update the code to test RecomVirtualCategory
        expect(instance).to.be.a(RecomaxRestApi.RecomVirtualCategory);
      });

      it('should have the property params (base name: "params")', function() {
        // TODO: update the code to test the property params
        expect(instance).to.have.property('params');
        // expect(instance.params).to.be(expectedValueLiteral);
      });

      it('should have the property rank (base name: "rank")', function() {
        // TODO: update the code to test the property rank
        expect(instance).to.have.property('rank');
        // expect(instance.rank).to.be(expectedValueLiteral);
      });

      it('should have the property recommendationId (base name: "recommendationId")', function() {
        // TODO: update the code to test the property recommendationId
        expect(instance).to.have.property('recommendationId');
        // expect(instance.recommendationId).to.be(expectedValueLiteral);
      });

    });
  });

}));
