/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecomaxRestApi);
  }
}(this, function(expect, RecomaxRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('StatusType', function() {
      beforeEach(function() {
        instance = new RecomaxRestApi.StatusType();
      });

      it('should create an instance of StatusType', function() {
        // TODO: update the code to test StatusType
        expect(instance).to.be.a(RecomaxRestApi.StatusType);
      });

      it('should have the property family (base name: "family")', function() {
        // TODO: update the code to test the property family
        expect(instance).to.have.property('family');
        // expect(instance.family).to.be(expectedValueLiteral);
      });

      it('should have the property reasonPhrase (base name: "reasonPhrase")', function() {
        // TODO: update the code to test the property reasonPhrase
        expect(instance).to.have.property('reasonPhrase');
        // expect(instance.reasonPhrase).to.be(expectedValueLiteral);
      });

      it('should have the property statusCode (base name: "statusCode")', function() {
        // TODO: update the code to test the property statusCode
        expect(instance).to.have.property('statusCode');
        // expect(instance.statusCode).to.be(expectedValueLiteral);
      });

    });
  });

}));
