/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecomaxRestApi);
  }
}(this, function(expect, RecomaxRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecomaxRestApi.EventApi();
  });

  describe('(package)', function() {
    describe('EventApi', function() {
      describe('createEventTestUsingPOST', function() {
        it('should call createEventTestUsingPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for createEventTestUsingPOST call and complete the assertions
          /*

          instance.createEventTestUsingPOST(, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(RecomaxRestApi.);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createEventUsingPUT', function() {
        it('should call createEventUsingPUT successfully', function(done) {
          // TODO: uncomment, update parameter values for createEventUsingPUT call and complete the assertions
          /*
          var opts = {};

          instance.createEventUsingPUT(, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(RecomaxRestApi.);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
